// Generated by CoffeeScript 1.11.1
(function() {
  var MongoClient, assert, authMechanism, authSource, express, f, password, request, router, secretValues, url, user;

  express = require('express');

  request = require('request');

  router = express.Router();

  MongoClient = require('mongodb').MongoClient;

  f = require('util').format;

  assert = require('assert');

  secretValues = require('./secretValues');

  user = encodeURIComponent(secretValues.secretValues.username);

  password = encodeURIComponent(secretValues.secretValues.password);

  authMechanism = 'DEFAULT';

  authSource = 'sikija';

  url = f('mongodb://%s:%s@133.130.103.96:27017/sikija?authMechanism=%s&authSource=%s', user, password, authMechanism, authSource);

  router.get('/jobs', function(req, res, next) {
    var link;
    link = 'http://job.ddhouse.co.kr/api/job/new?area=&theme=';
    return request({
      method: 'GET',
      uri: link,
      encoding: null
    }, function(err, response, body) {
      return res.send(body.toString().trim());
    });
  });

  module.exports = router;

  router.get('/restaurants', function(req, res, next) {
    var condition;
    condition = {};
    return MongoClient.connect(url, function(err, db) {
      var delivery;
      assert.equal(null, err);
      delivery = db.collection('dashboard');
      delivery.find(condition).toArray(function(err, docs) {
        return res.send(docs[0]['restaurants']);
      });
      return db.close;
    });
  });

}).call(this);

//# sourceMappingURL=dashboard.js.map
